### ISSUE TITLE
Got an unexpected error. Please redirect the following message to the devs: JDA 4.4.0_350

### ISSUE THREAD

**Issue by MineTrainDevelopment** [DV8FromTheWorld/JDA#2303] opened 2022-10-24 17:09 UTC
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

All the checkboxes above are a lie, bcs i have to check them.
The Stack trace said, is should send you this, so i do it.
![image](https://user-images.githubusercontent.com/83841861/197583449-d4cbbba9-201b-4961-bb1e-36db00db20ee.png)
![image](https://user-images.githubusercontent.com/83841861/197584819-39d10670-8a48-4b2f-be6f-baaf34eb8c5a.png)

### Code Example for Reproduction Steps

```java
...
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
DefaultShardManagerBuilder builder = DefaultShardManagerBuilder.createDefault(null);
builder.setToken(config.getJdaToken());
builder.setEnableShutdownHook(config.isJdaShutdownHook);
builder.setStatus(OnlineStatus.IDLE);
builder.setActivity(Activity.playing("Server startet..."));
builder.addEventListeners(new ButtonEvent());
builder.addEventListeners(new SlashCommandListner());
```

**Comment by Andre601** [comment] 2022-10-24 19:11
`IllegalStateException: Zip file closed`
This is a common exception happening on Bukkit/Spigot/Paper servers. It's caused by the server closing the Jar file (unloading it) before JDA had time to fully shut down.

Either perform a `shutdownNow()` call in your plugin's `onDisable()` void, or delay further actions through a Thread.sleep action.

Related issues: #1761, #1771, #1780, #1861, #2197, #2205 and #2217

**Closed** 2022-10-24 19:36 UTC
