### ISSUE TITLE
java.lang.NoClassDefFoundError: net.dv8tion.jda.core.JDABuilder

### ISSUE THREAD

**Issue by MysticOverlord** [DV8FromTheWorld/JDA#1005] opened 2019-05-10 19:25 UTC
I am currently trying to setup my bot in a server and i get this error in the server output which doesn't show when i run the same program on eclipse! 
`Exception in thread "main" java.lang.NoClassDefFoundError: net.dv8tion.jda.core.JDABuilder`
Only small difference in the project files is that i packaged the maven project into a manifest .jar file!

**Comment by MinnDevelopment** [comment] 2019-05-10 20:35
Closing as duplicate of #101 and #679 
This is not the place to learn how to build a jar.

The github issue tracker is reserved for feature requests and bug reports. Your issue is neither and should be sorted out inside of our discord server. Go to [discord.gg/0hMr4ce0tIl3SLv5](https://discord.gg/0hMr4ce0tIl3SLv5) to receive the needed help.

**Closed by MinnDevelopment** 2019-05-10 20:35 UTC

**Comment by alphawerewolf1900** [comment] 2020-02-08 03:08
you need to make more than one java file than export as a jar file
