### ISSUE TITLE
Massively distorted audio on some files

### ISSUE THREAD

**Issue by anilbanarsee** [DV8FromTheWorld/JDA#55] opened 2016-05-16 22:11 UTC
I have been testing out the sending audio part of the api.

It works great aside from for some files where it is horribly distorted.

For example :

https://hydra-media.cursecdn.com/dota2.gamepedia.com/4/42/Bane_spawn_01.mp3

(I downloaded it and used the FilePlayer not URLPlayer)

was massively distorted for me

If it helps, I checked the bitrate on that file, 64kbps. The files it worked well on were around 200kbps

Another file which was very distorted was a .wav file with 700+ kbps bitrate

**Comment by happygecko** [comment] 2016-05-16 23:25
The 700+ kbps wav would make since since that is a lot data to send. Most internet radio stations/DJs stream around 256-320kbps, so 700+ kbps would seem pretty extreme for he voice servers to handle well.

The 64kbps is strange though. Have you seen anyone else around the net complain about low bitrate audio files with other APIs or Java in general? Might possibly be a Discord/Java bug.

**Comment by MinnDevelopment** [comment] 2016-05-17 09:39
Did you get a similar problem with files that contained more than 3 seconds of audio? It could just be a buffer issue atm

**Comment by DV8FromTheWorld** [comment] 2016-05-18 19:03
The issue is that this is a mono file. Currently, JDA expects everything to be stereo audio.
For now, the quick fix would be to re-encode the file as stereo. In the future I'll be adding support for mono sources hopefully.

**Comment by DV8FromTheWorld** [comment] 2016-05-22 15:03
Closing this as it has been explained and there has been no active conversation. Re-open if there is something more that you wish to discuss.

**Closed by DV8FromTheWorld** 2016-05-22 15:03 UTC
