### ISSUE TITLE
Very Distorted Audio When Playing Short Files

### ISSUE THREAD

**Issue by intoxicatedpenguin** [DV8FromTheWorld/JDA#129] opened 2016-09-17 17:11 UTC
If I play a short mp3, that seems to be if it's less than 30 seconds, it turns out VERY distorted and sounds awful. I read in another issue that it might be if the audio was mono, so I converted all audio to stereo, but that's not it. I have verified that the mp3 sounds normal if played outside the bot.
Here's the code that pertains to playing:
```
            event.getTextChannel().sendMessage("Playing " + video.title + " ID is " + video.id);
			File audioFile  = null;
			try {

				System.out.println("playing!");
				audioFile = new File(video.id+".mp3");
				System.out.println(audioFile.getName());
				player = new FilePlayer(audioFile);
				TimerTask playerStop = new PlayerStop(player);
				event.getGuild().getAudioManager().setSendingHandler(player);
				player.play();
				t.schedule(playerStop, (long) video.duration*1000);
				System.out.println("Scheduled player to stop in " + (long) video.duration + " seconds!");
			} catch (IOException | UnsupportedAudioFileException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
```
If needed I'll give a comparison of the mp3 being played and the audio that actually is played.

**Comment by DV8FromTheWorld** [comment] 2016-09-18 01:52
Can you please upload an example file for me to test with?

**Comment by intoxicatedpenguin** [comment] 2016-09-18 06:39
Yeah, here's a link to an mp3 that does it, as github won't let me upload it. 
http://harambe.moe/memes/qwrfcKoAti.mp3

**Comment by DV8FromTheWorld** [comment] 2016-09-18 21:35
The file provided sounds incredibly distorted or like a baby animal crying when I play it not using JDA (i played it through Chrome).
When playing it using JDA-Player it sounds identical to how it sounds in chrome.

**Comment by intoxicatedpenguin** [comment] 2016-09-19 11:06
Does it sound like this though? 
http://harambe.moe/memes/RViCst14Dq.webm

**Comment by DV8FromTheWorld** [comment] 2016-09-20 06:18
Nope. Additionally: The problem isn't that it is a short clip. The issue is that it is Mono. If you convert it to Stereo it should work just fine.
As a note, this is only an issue with JDA's prebuilt Player system (e.g: Player, FilePlayer, and URLPlayer).
These 3 classes are being removed in JDA 3.x so I would highly advise not using them.

For an alternative solution for an Audio Player, I would highly recommend [JDA-Player](https://github.com/DV8FromTheWorld/JDA-Player).

**Comment by intoxicatedpenguin** [comment] 2016-09-20 11:01
Okay, I'll try that. Thank you.

**Comment by DV8FromTheWorld** [comment] 2016-09-20 14:03
Closing this as an answer has been provided. If you have further issue, feel free to reopen.

**Closed by DV8FromTheWorld** 2016-09-20 14:03 UTC
