### ISSUE TITLE
Max bitrate exception

### ISSUE THREAD

**Issue by thetakodev** [DV8FromTheWorld/JDA#1096] opened 2019-09-12 18:44 UTC
## General Troubleshooting

  
- [x ] I have checked for similar issues.
- [x ] I have updated to the [latest JDA version][download].
- [ x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

When bitrate is set to greater than 128000 it throws an exception that 128000 is max
and when set below that but above 96000, discord api errors.
Also server boosts unlock up to 384kbs bitrate so that should be a feature

### Exception or Error

```
[JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at team.kuki.kada.AnnotationHandler.onGenericEvent(AnnotationHandler.kt:19)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:318)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:64)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:148)
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:838)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:737)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:716)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:876)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.IllegalArgumentException: Bitrate must be less than 128000
	at net.dv8tion.jda.internal.requests.restaction.ChannelActionImpl.setBitrate(ChannelActionImpl.java:195)
	at net.dv8tion.jda.internal.requests.restaction.ChannelActionImpl.setBitrate(ChannelActionImpl.java:38)
	at team.kuki.kukibot.Test.vctest(Test.kt:12)
	... 21 more
```

**Comment by MinnDevelopment** [comment] 2019-09-22 11:19
Closing since I can't reproduce it and this issue is not getting updated.

**Closed by MinnDevelopment** 2019-09-22 11:19 UTC
Labels: status: need more info
