### ISSUE TITLE
Timeouts in JDAAudioConn cause the whole bot to halt.

### ISSUE THREAD

**Issue by Kodehawa** [DV8FromTheWorld/JDA#338] opened 2017-04-29 14:03 UTC
As reported in JDA, adjunted Thread Dump.

[dump1.txt](https://github.com/DV8FromTheWorld/JDA/files/966171/dump1.txt)

When the connection to singapore20.discordapp.gg (replace 20 by any number really)
due to a OVH trace route error with networklayer fails and times out, the entire WS halts, causing the bot to only reply on the limited instances where the bot can actually connect to that URL. (A example being: http://i.imgur.com/TYosYAv.png).

As I've been reported, an audio connection timeout shouldn't actually halt the whole bot from replying.

Console looked like this: https://cdn.discordapp.com/attachments/125227483518861312/307882426875510794/unknown.png

**Comment by MinnDevelopment** [comment] 2017-04-29 14:39
This timeout causes the VoiceServerUpdateHandler to lock for the time it connects. Due to the time it takes to connect the ReadingThread is locked and events cannot be processed.
See [VoiceServerUpdateHandler.java#L68-L88](https://github.com/DV8FromTheWorld/JDA/blob/98bfcb963a6a25364f8bbddf210034723415a005/src/main/java/net/dv8tion/jda/core/handle/VoiceServerUpdateHandler.java#L68-L88)

**Comment by DV8FromTheWorld** [comment] 2017-05-01 01:39
Are you implying that the sync lock should be done not in the WS ReadingThread?

**Comment by MinnDevelopment** [comment] 2017-05-01 04:33
The issue is not the sync lock the issue is the blocking call to WebSocket#connect in the AudioWebSocket constructor

**Comment by MinnDevelopment** [comment] 2017-05-01 04:36
The connecting should be done in a separate method of AudioWebSocket after creating the AudioWebSocket and the AudioConnection.
The method itself should be using the WebSocket#connectAsynchronously() method.

**Comment by MinnDevelopment** [comment] 2017-05-01 12:28
I have proof that the sync lock also causes issues with JDA#shutdown where the thread calling is awaiting the connection to be established before then closing it. However I was reported a case where the connection could not establish breaking the shutdown and causing a block for over 15 minutes.

**Comment by MinnDevelopment** [comment] 2017-05-01 12:30
I'm marking this as priority as it is the reason for 3 issues:
- Connection Timeout blocking event handling
- AudioConnection being null for speaking updates (needs to connect after setting connection)
- Locking shutdown thread

**Comment by DV8FromTheWorld** [comment] 2017-05-01 14:46
Okay, will refocus.on these issues.

**Comment by DV8FromTheWorld** [comment] 2017-05-04 06:14
Fix has been deployed to a bug branch.
Please try the fix: https://jitpack.io/#DV8FromTheWorld/JDA/bug~audio-lock-fix-SNAPSHOT

**Comment by Kodehawa** [comment] 2017-05-05 12:58
Will do now and report back.

**Closed** 2017-05-08 21:54 UTC
Labels: bug, In Progress, priority
