### ISSUE TITLE
Update to new JDA ...

### ISSUE THREAD

**Issue by Vladimir-Urik** [DV8FromTheWorld/JDA#1341] opened 2020-07-08 14:02 UTC
After updating to the latest JDA library, it writes me this error:
```
Exception in thread "main" java.lang.IllegalArgumentException: Listener must implement EventListener
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.register(InterfacedEventManager.java:62)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.register(EventManagerProxy.java:52)
        at net.dv8tion.jda.internal.JDAImpl.addEventListener(JDAImpl.java:810)
        at net.dv8tion.jda.api.JDABuilder.lambda$build$0(JDABuilder.java:1841)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1841)
        at me.Thumbie.Core.main(Core.java:145)
```

Core:145 is `builder.build();`

**Comment by MinnDevelopment** [comment] 2020-07-08 14:03
Duplicate of #1340

**Closed by MinnDevelopment** 2020-07-08 14:03 UTC

**Comment by Andre601** [comment] 2020-07-08 14:15
Please do follow the issue templates as mentioned in #1337 (Minn even linked to it in your previous issue).
The templates exist for a reason and shouldn't be ignored, otherwise, your issue will be closed without further actions (This is again explained in the linked issue)
