### ISSUE TITLE
On message send

### ISSUE THREAD

**Issue by RetamrCZ** [DV8FromTheWorld/JDA#2205] opened 2022-08-05 20:34 UTC
### General Troubleshooting

- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.
- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)

### Expected Behaviour

Dont have error xd

### Code Example for Reproduction Steps

```java
N/A
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
N/A
```

### Exception or Error

```yesyes
[22:31:14 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect the following message to the devs:
        JDA 5.0.0-alpha.17_13194f3
        MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"components":[],"attachments":[],"author":{"public_flags":128,"id":"798598816273137685","avatar":"95f0acd3dc820d15e812efbfa4a1a20e","username":"RETAMROVEC","discriminator":"1262","avatar_decoration":null},"flags":0,"type":0,"mention_roles":[],"nonce":"1005211379277234176","edited_timestamp":null,"content":"","tts":false,"referenced_message":null,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2022-07-08T15:48:30.781000+00:00","communication_disabled_until":null,"roles":["995004651596431460","995008094721556620","1001106616193654864","995006718981443666","995006534381740053","995988521967960154"],"pending":false,"flags":0,"deaf":false,"mute":false,"avatar":null},"guild_id":"994988088042471507","id":"1005211401746399362","embeds":[],"channel_id":"995007041242415255","timestamp":"2022-08-05T20:31:14.101000+00:00"}
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:37) ~[FeedBack-1.19-V1.jar:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[FeedBack-1.19-V1.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) ~[FeedBack-1.19-V1.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) ~[FeedBack-1.19-V1.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) ~[FeedBack-1.19-V1.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) ~[FeedBack-1.19-V1.jar:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[FeedBack-1.19-V1.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[FeedBack-1.19-V1.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[FeedBack-1.19-V1.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[FeedBack-1.19-V1.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[FeedBack-1.19-V1.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[FeedBack-1.19-V1.jar:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[FeedBack-1.19-V1.jar:?]
```

**Comment by MinnDevelopment** [comment] 2022-08-05 20:42
Duplicate of #2197 #1429 #1440 #1761 #1771 #1780 #1861

**Closed by MinnDevelopment** 2022-08-05 20:42 UTC
