### ISSUE TITLE
Events Not Works

### ISSUE THREAD

**Issue by Sywoo-Dev** [DV8FromTheWorld/JDA#1411] opened 2020-10-07 15:19 UTC
Hello, on the event "onGuildMessageReactionRemove" the user and member are null
`	@Override
	public void onGuildMessageReactionRemove(GuildMessageReactionRemoveEvent event) {
		if(event.getMessageIdLong() == accessID) {
			Role role = event.getGuild().getRoleById(reactionsRoles.get(event.getReaction().getReactionEmote().getEmoji()));
			if(role == null) {
				event.getReaction().removeReaction().complete();
				return;
			}
			event.getGuild().removeRoleFromMember(event.getMember(), role);
		}
	}`

"event.getMember() return a NPE"

Event of Join and Leave a Guild there never called, i have print all GenericEvent and All GuildGenericEvents and never seen them.

by the way this event isn't work

`	@Override
	public void onGuildMemberJoin(GuildMemberJoinEvent event) {
		Member newMember = event.getMember();
		System.out.println(newMember.getNickname() + " Has Join");

		new UserUtils().sendPrivateMessage(newMember.getUser(), "Bienvenue sur le serveur du studio Asteria");
		event.getGuild().addRoleToMember(newMember, event.getJDA().getRoleById(Long.valueOf("762976778506600498"))).complete();
		
	}`

Thanks for reading in wait of fix

**Comment by MinnDevelopment** [comment] 2020-10-07 15:23
Duplicate of #1261 #1275 #1300

The leave event is deprecated. And you should use `GuildMemberRemoveEvent` instead. And read the [Troubleshooting Guide](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#my-event-listener-code-is-not-executed)

Closing due to #1337

**Closed by MinnDevelopment** 2020-10-07 15:23 UTC

**Comment by Sywoo-Dev** [comment] 2020-10-07 15:29
> 
> 
> Duplicate of #1261 #1275 #1300
> 
> The leave event is deprecated. And you should use `GuildMemberRemoveEvent` instead. And read the [Troubleshooting Guide](https://github.com/DV8FromTheWorld/JDA/wiki/19%29-Troubleshooting#my-event-listener-code-is-not-executed)
> 
> Closing due to #1337

i'm trying to use "GuildMemberRemoveEvent" to detect server leave thak you.

but for the event when you delete your own reaction, the getter of member return null how i can do, because getUserIdLong return a Long but it's not match with an existing Guild Member

**Comment by Andre601** [comment] 2020-10-07 16:14
Discord doesn't provide enough information for the ReactionRemoveEvent to get a member reliably. Members also require the GUILD_MEMBER intent to be enabled and used and the Members to be cached.
The value returned by getUserIdLong is - according to the docs - the ID of the user who added or removed the reaction, but it basically boils down to what Discord is returning.

The GuildMemberLeaveEvent is - as Minn said - deprecated. You should instead use the GuildLeaveEvent if you want to detect your bot leaving a server.
