### ISSUE TITLE
javadocs detected as trojan

### ISSUE THREAD

**Issue by lever1209** [DV8FromTheWorld/JDA#1673] opened 2021-06-16 10:55 UTC
every time i try using javadocs from this project, chrome, windows defender, and avast keep saying its a trojan, so i cant use the javadocs without them getting deleted on me after 15 minutes

**Comment by duncte123** [comment] 2021-06-16 10:57
You can use the online docs https://ci.dv8tion.net/job/JDA/javadoc/

**Comment by Andre601** [comment] 2021-06-16 10:57
1. Works perfectly fine for me
   ![image](https://user-images.githubusercontent.com/11576465/122207314-4904b080-cea2-11eb-817b-4b5b8a8c7a34.png)
2. Did you use the right URL? It's https://ci.dv8tion.net/job/JDA/javadoc/
3. Use a better anti-virus... I guess
4. Follow the issue template: #1337

**Comment by MinnDevelopment** [comment] 2021-06-16 10:58
Duplicate of #873 #1352 #1402

**Closed by MinnDevelopment** 2021-06-16 10:58 UTC
