### ISSUE TITLE
Unexpected error : CHANNEL_UPDATE -> ... java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by one-dev-man** [DV8FromTheWorld/JDA#2446] opened 2023-04-15 09:07 UTC
### General Troubleshooting

- [x] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

I think JDA doesn't parse correctly a response from the Discord API. Maybe the websocket client ?
Moreover, this error happened when I updated the name of some channels on my discord server, and the error happened each time I updated any channel name.
If you can explain why this error happen and how to solve it, I would be delighted !

- Context : creation of an authentication minecraft plugin -> want to introduce a 2FA way through discord.
- The JDA version used : 5.0.0-beta.8 from the Bintray Maven Central (http://jcenter.bintray.com)
- Spigot version used : 1.19.3-R0.1-SNAPSHOT from the Spigot Nexus Snapshot repository (https://hub.spigotmc.org/nexus/content/repositories/snapshots/)
- Minecraft server used to test the plugin : Paper 1.19.4 build 510

### Code Example for Reproduction Steps

```java
Nothing in particular, the bug happened by itself from JDA directly (no stacktrace from my own code, only from JDA).
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
package org.onedevman.mc.plugins.passcraft.authentication;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.events.interaction.component.ButtonInteractionEvent;
import net.dv8tion.jda.api.events.message.MessageReceivedEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import org.bukkit.Bukkit;
import org.onedevman.mc.plugins.passcraft.database.DatabaseManager;
import org.onedevman.mc.plugins.passcraft.utils.types.Pair;
import org.onedevman.mc.plugins.passcraft.utils.types.Trio;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

public class DiscordAuthenticator extends ListenerAdapter {

    public final DatabaseManager dbmanager;

    public final String dbtable;

    public final String usercolumn;
    public final String discordcolumn;

    public final JDA discordClient;

    //

    private final Map<String, Pair<String, Consumer<Boolean>>> registering_request_map = new HashMap<>();

    //

    public DiscordAuthenticator(DatabaseManager dbmanager, String dbtable, String usercolumn, String discordcolumn, String token) throws InterruptedException, SQLException {
        this.dbmanager = dbmanager;

        this.dbtable = dbtable;

        this.usercolumn = usercolumn;
        this.discordcolumn = discordcolumn;

        Bukkit.getLogger().info("||| DISCORD `" + this.dbtable + "` ; `" + this.usercolumn + "` ; `" + this.discordcolumn + "`");

        //

        this.discordClient = JDABuilder.createDefault(token).build();

        this.discordClient.awaitReady();
        this.discordClient.addEventListener(this);

        //

        ...
    }

    //

    ...

    //

    ...

    //

    @Override
    public void onMessageReceived(MessageReceivedEvent event) {
        try {
            this.handleRegisteringRequest(event);
        } catch(SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void handleRegisteringRequest(MessageReceivedEvent event) throws SQLException {
        String otp = event.getMessage().getContentRaw();
        Pair<String, Consumer<Boolean>> registering_request = this.registering_request_map.remove(otp);

        String user = registering_request.first();

        String user_discord = event.getMessage().getAuthor().getAsTag();

        Bukkit.getLogger().info("||| `" + user_discord + "`");

        if(registering_request == null)
            return;
        
        ...
    }

    //

    @Override
    public void onButtonInteraction(ButtonInteractionEvent event) {

    }

    ...

}
```

### Exception or Error

```yesyes
[JDA MainWS-ReadThread/ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect the following message to the devs:
	JDA 5.0.0-beta.8_d8d2df6
	CHANNEL_UPDATE -> ...
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.dv8tion.jda.internal.handle.ChannelUpdateHandler.handleInternally(ChannelUpdateHandler.java:108) ~[passcraft-0.0.1-dev.jar:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[passcraft-0.0.1-dev.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:985) ~[passcraft-0.0.1-dev.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:871) ~[passcraft-0.0.1-dev.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:849) ~[passcraft-0.0.1-dev.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1024) ~[passcraft-0.0.1-dev.jar:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[passcraft-0.0.1-dev.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[passcraft-0.0.1-dev.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[passcraft-0.0.1-dev.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[passcraft-0.0.1-dev.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[passcraft-0.0.1-dev.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[passcraft-0.0.1-dev.jar:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[passcraft-0.0.1-dev.jar:?]
```

**Comment by MinnDevelopment** [comment] 2023-04-15 09:17
Duplicate of #1429 #1440 #1761 #1771 #1780 #1861 #2197 #2217 #2303

See also https://jda.wiki/using-jda/troubleshooting/#illegalstateexception-zip-file-closed

**Closed by MinnDevelopment** 2023-04-15 09:17 UTC

**Comment by one-dev-man** [comment] 2023-04-15 09:30
Ok, thanks @MinnDevelopment !
