### ISSUE TITLE
Music playing too fast

### ISSUE THREAD

**Issue by NayKeys** [DV8FromTheWorld/JDA#1248] opened 2020-04-02 18:39 UTC
I dont know why, everything is working well (except adding a playlist) but each video (from youtube) that i'm trying to play is readed in 2x speed ! Also in every guild (and new guilds too) !
I'm using the acutal last version of lavaplayer and JDA 4.1.1_127

**Comment by MinnDevelopment** [comment] 2020-04-02 18:46
Without any code or reproduction step I can't help you. We have this bug report issue template for a reason.

You probably just used the same player with multiple send handlers or used the same send handlers for multiple connections. In all cases I can only guess what you're doing since you didn't add any useful details to make a clear diagnosis of the issue.

**Comment by NayKeys** [comment] 2020-04-03 17:20
Ok, i am sorry,
Here is my queue method : https://i.imgur.com/1UYe5f9.png (tracks is a java.util LinkedBlockingQueue)

Here is my AudioSendHandler class : https://i.imgur.com/AGophlU.png

And i'm not supposed to used same handler for multiple connections cuz i'm using this method : getPlayer() : https://i.imgur.com/DZX2ceQ.png

**Comment by Devoxin** [comment] 2020-04-03 17:22
You're calling `provide()` twice. (JDA calls `canProvide()`, and you're calling it again in `provide20MsAudio()`).

**Comment by MinnDevelopment** [comment] 2020-04-03 17:49
Closing since this is not a JDA issue. You should only call provide once though.

**Closed by MinnDevelopment** 2020-04-03 17:49 UTC
