### ISSUE TITLE
getMessageContentRow() from message in MessageDeleteEvent

### ISSUE THREAD

**Issue by OMAR-3OOV** [DV8FromTheWorld/JDA#2166] opened 2022-06-27 07:28 UTC
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Hey jda.

I was working using the MessageDeleteEvent and I really want to get the deleted message content, if you wondering why I didn't use the AuditLog, it's because of the message from privateChannel i can't get the content so I wonder if you can add a future that gives message content, this will make this event really useful and less work for others to get the message content without calling auditlog

### Example Use-Case

```java
public String getMessageContentRow() {
   return message.getContentRow();
}
```

**Comment by caneleex** [comment] 2022-06-27 07:33
discord doesn't provide the deleted message content in update and delete events. additionally, audit logs don't store the old content either.

**Comment by MinnDevelopment** [comment] 2022-06-27 07:38
Duplicate of #569

**Closed by MinnDevelopment** 2022-06-27 07:38 UTC

**Comment by OMAR-3OOV** [comment] 2022-06-27 07:44
I know they won't store it, but jda could store instead... it's really useful think

**Comment by Tais993** [comment] 2022-06-27 07:52
JDA is meant as an API wrapper, not a full-framework.
If you want it, you can easily store it yourself.

**Comment by OMAR-3OOV** [comment] 2022-06-27 07:55
for now, I have already stored it, so what about the user ? i can't get the user if it's normal channel ( not privateChannel )

**Comment by Tais993** [comment] 2022-06-27 07:58
Discord doesn't give you that information either, JDA cannot give it either.
There's 2 users in the channel, the bot and the user. So figure something out so you know whenever the bot (you) deleted.
