### ISSUE TITLE
ErrorResponseException after trying to send a message

### ISSUE THREAD

**Issue by d1snin** [DV8FromTheWorld/JDA#1542] opened 2021-03-11 12:44 UTC
The problem is that when I try to write a private message to the user, an ErrorResponseException is thrown, I am trying to send a message to the newly registered user. For some reason this message is being sent to my friend, but still I see an ErrorResponseException in the log, I am using the latest version of JDA
Code:
```java
package xyz.d1snin.emily.commands;

import net.dv8tion.jda.api.Permission;
import net.dv8tion.jda.api.entities.Member;
import net.dv8tion.jda.api.entities.User;
import net.dv8tion.jda.api.events.message.MessageReceivedEvent;
import xyz.d1snin.emily.Emily;
import xyz.d1snin.emily.util.EmbedUtils;
import java.util.Arrays;
import java.util.List;

public class KickCommand extends Command {
    private static String reason = "";

    @Override
    public void onCommand(MessageReceivedEvent e, String[] args) {
        if (!e.getMember().hasPermission(Permission.KICK_MEMBERS)) {
            EmbedUtils.sendEmbed(e, "You dont have permission to use this command.");
            return;
        }
        if (args.length < 2) {
            EmbedUtils.sendEmbed(e, "Please use the following syntax: " + "`" + Emily.BOT_PREFIX + "kick` `<mentionTheUser>` `<Reason>`");
            return;
        }
        try {
            List<Member> mentionedMembers = e.getMessage().getMentionedMembers();
            Member target = mentionedMembers.get(0);
            List<User> privateMessage = e.getMessage().getMentionedUsers();
            User privatemsg = privateMessage.get(0);
            for (int i = 2; i < args.length; i++) {
                reason += args[i] + " ";
            }
            target.kick().queue();
            EmbedUtils.sendEmbed(e, "User " + target.getAsMention() + " has been kicked by " + e.getAuthor().getAsMention() + "\nReason: " + reason);
            sendPrivateMessage(privatemsg, e);

        } catch (IndexOutOfBoundsException indexOutOfBoundsException) {
            EmbedUtils.sendEmbed(e, "There is no such user in this guild");
        }
        reason = "";
    }
    private void sendPrivateMessage(User user, MessageReceivedEvent e) {
        user.openPrivateChannel().queue((channel) ->
                EmbedUtils.sendPrivateEmbed(channel, "You have been kicked from the server " + e.getGuild().getName() + " by " + e.getAuthor().getAsMention() + "\nReason: " + reason));
    }

    @Override
    public List<String> getAliases() {
        return Arrays.asList(Emily.BOT_PREFIX + "kick");
    }

    @Override
    public String getDescription() {
        return "Kick a member";
    }

    @Override
    public String getCategory() {
        return "Moderation";
    }

}
```
Log output:
```
[ForkJoinPool.commonPool-worker-0] ERROR RestAction - RestAction queue returned failure: [ErrorResponseException] 50007: Cannot send messages to this user
net.dv8tion.jda.api.exceptions.ContextException
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:563)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:529)
        at xyz.d1snin.emily.util.EmbedUtils.sendPrivateEmbed(EmbedUtils.java:40)
        at xyz.d1snin.emily.commands.KickCommand.lambda$sendPrivateMessage$0(KickCommand.java:44)
        at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:95)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

```

**Comment by arynxd** [comment] 2021-03-11 12:46
You can't send messages to a user if you just kicked them from a guild, unless you share another server.

**Comment by MinnDevelopment** [comment] 2021-03-11 12:47
The problem is that the bot doesn't share a server with the target user after kicking them. You should kick in the queue callback of your sendMessage action.

Closing due to #1337

**Closed by MinnDevelopment** 2021-03-11 12:47 UTC

**Comment by d1snin** [comment] 2021-03-11 12:54
thank you!
