### ISSUE TITLE
Breaking Fatal on Bot Setup

### ISSUE THREAD

**Issue by AlexSafatli** [DV8FromTheWorld/JDA#484] opened 2017-09-25 13:50 UTC
```
2017-09-25 10:45:57.505 ERROR 27464 --- [inWS-ReadThread] n.d.jda.core.requests.WebSocketClient    : Completed the setup for Guild: G:Tasty Invisible Space Station(153001169793449984) without matching id in ReadyHandler cache
2017-09-25 10:45:57.506 ERROR 27464 --- [inWS-ReadThread] n.d.jda.core.requests.WebSocketClient    : Got an unexpected error. Please redirect following message to the devs:
	GUILD_CREATE -> {"default_message_notifications":0,"unavailable":false,"owner_id":"151162831235055616","roles":[{"color":0,"permissions":37215297,"managed":false,"name":"@everyone","mentionable":false,"position":0,"id":"153001169793449984","hoist":false},{"color":10181046,"permissions":1140325631,"managed":false,"name":"Patricians","mentionable":false,"position":6,"id":"165948769978810368","hoist":true},{"color":15158332,"permissions":238550080,"managed":false,"name":"Slave","mentionable":false,"position":1,"id":"168819663415934976","hoist":true},{"color":2123412,"permissions":37014592,"managed":false,"name":"Plebs","mentionable":true,"position":3,"id":"168857882836729856","hoist":true},{"color":15844367,"permissions":37215297,"managed":false,"name":"Liberti","mentionable":true,"position":5,"id":"196030219512053760","hoist":true},{"color":16752122,"permissions":37215297,"managed":false,"name":"George Foreman","mentionable":false,"position":2,"id":"252632586789191680","hoist":true},{"color":2067276,"permissions":37215297,"managed":false,"name":"Nobilis","mentionable":true,"position":4,"id":"361857158024921099","hoist":true}],"icon":"0bc370501327967cb336fadb53991f27","system_channel_id":null,"afk_timeout":900,"features":[],"presences":[{"game":null,"user":{"id":"95498818501488640"},"status":"online"},{"game":null,"user":{"id":"151162831235055616"},"status":"online"},{"game":null,"user":{"id":"172072798347329536"},"status":"online"},{"game":null,"user":{"id":"292693785421414410"},"status":"online"}],"afk_channel_id":"258412730480984068","members":[{"joined_at":"2016-08-16T20:32:11.093000+00:00","roles":["196030219512053760"],"deaf":false,"mute":false,"user":{"id":"95498818501488640","avatar":"b723bd80bc41476eff9d6f45710425c2","username":"Axyl","discriminator":"0924"}},{"nick":null,"joined_at":"2016-02-27T04:52:01.507000+00:00","roles":["165948769978810368"],"deaf":false,"mute":false,"user":{"id":"151162831235055616","avatar":"bb767d4a1704c267bf128c2a5a6eb01d","username":"Asaph","discriminator":"6359"}},{"nick":null,"joined_at":"2016-04-14T21:36:39.277000+00:00","roles":["168819663415934976"],"deaf":false,"mute":false,"user":{"id":"165531501755105281","avatar":"89df7ca86e0fa232eca3060126e8dbab","username":"Recaso","discriminator":"5379"}},{"joined_at":"2016-06-12T01:00:56.763000+00:00","roles":["165948769978810368"],"deaf":false,"mute":false,"user":{"id":"165531670038970368","avatar":"bf143e1905131b2aad5d8d9965eadf80","username":"Kirjava","discriminator":"8618"}},{"joined_at":"2016-04-10T22:33:17.883000+00:00","roles":["196030219512053760"],"deaf":false,"mute":false,"user":{"id":"165535022286110730","avatar":"2bf37be987a63859e4055ee7e822bad6","username":"Busby","discriminator":"4002"}},{"joined_at":"2016-06-22T20:24:53.894000+00:00","roles":["196030219512053760"],"deaf":false,"mute":false,"user":{"id":"165537415425949696","avatar":"0852af876c61e55121e784d3f7e05da8","username":"Thorno","discriminator":"8140"}},{"joined_at":"2016-04-01T22:10:03.756000+00:00","roles":["165948769978810368"],"deaf":false,"mute":false,"user":{"id":"165578048165380096","avatar":"852d3632fb9edf8085f2f2efed483785","username":"Nepo","discriminator":"4891"}},{"joined_at":"2016-04-01T22:09:45.799000+00:00","roles":["165948769978810368"],"deaf":false,"mute":false,"user":{"id":"165579082518495241","avatar":"8f0768f1d1276d1fcee2c988215f8f8b","username":"Aerozap","discriminator":"3613"}},{"joined_at":"2016-08-30T19:55:28.006000+00:00","roles":["196030219512053760"],"deaf":false,"mute":false,"user":{"id":"167374445655097356","avatar":"527e2ec69535aa9909eb2a0601fd781a","username":"Mantaray","discriminator":"9545"}},{"joined_at":"2016-04-15T03:17:15.727000+00:00","roles":["252632586789191680"],"deaf":false,"mute":false,"user":{"id":"170371727656878080","avatar":"303260f3789b69ff70e3a375c8e198a5","username":"Harlequin Rouge","discriminator":"9554"}},{"nick":null,"joined_at":"2017-02-17T23:19:32.041000+00:00","roles":["168819663415934976"],"deaf":false,"mute":false,"user":{"bot":true,"id":"172072798347329536","avatar":"2667450a4bcf38c4e1469a92469b2f7e","username":"Garrus Vakarian","discriminator":"6036"}},{"nick":null,"joined_at":"2017-04-22T20:29:53.924188+00:00","roles":["168857882836729856"],"deaf":false,"mute":false,"user":{"id":"178283409288855553","avatar":"fd02bd62ab04bf96f8fa7c8e1ac085a8","username":"TDPenguin2","discriminator":"3927"}},{"joined_at":"2016-06-22T20:29:07.164000+00:00","roles":["168857882836729856"],"deaf":false,"mute":false,"user":{"id":"178843282393137152","avatar":"c0fa0477953388e1d45e0ab41fb98385","username":"DStow","discriminator":"3020"}},{"joined_at":"2016-10-30T19:38:27.673000+00:00","roles":["196030219512053760"],"deaf":false,"mute":false,"user":{"id":"180735576180391936","avatar":"4f6ca18a9f2a13060f9b7301ab1dcdf9","username":"Raddish","discriminator":"1372"}},{"nick":null,"joined_at":"2017-08-25T21:05:31.681577+00:00","roles":["196030219512053760"],"deaf":false,"mute":false,"user":{"id":"196376650584293378","avatar":"9ce0bdaa7dc45fe8d0d0fb074fb9a040","username":"Käzmar","discriminator":"2833"}},{"nick":null,"joined_at":"2017-04-21T17:08:50.079223+00:00","roles":["168857882836729856"],"deaf":false,"mute":false,"user":{"id":"202851633590173696","avatar":"4e58bd11c6d93b1f6ffdf65c6ef7c691","username":"Theero","discriminator":"9823"}},{"joined_at":"2017-03-18T16:22:18.941000+00:00","roles":["168857882836729856"],"deaf":false,"mute":false,"user":{"id":"292693785421414410","avatar":null,"username":"JuicyJuicyMango","discriminator":"8386"}},{"nick":"Wierdoom","joined_at":"2017-09-24T22:05:29.935643+00:00","roles":["361857158024921099"],"deaf":false,"mute":false,"user":{"id":"361633717229191168","avatar":null,"username":"more dread","discriminator":"1050"}}],"voice_states":[],"id":"153001169793449984","member_count":18,"emojis":[{"managed":false,"roles":[],"name":"SMOrc","id":"258419591724793856","require_colons":true},{"managed":false,"roles":[],"name":"biblethump","id":"258420146513772544","require_colons":true},{"managed":false,"roles":[],"name":"4Head","id":"260527820717948928","require_colons":true},{"managed":false,"roles":[],"name":"OSfrog","id":"292809347400990730","require_colons":true},{"managed":false,"roles":[],"name":"PogChamp","id":"292810749674389506","require_colons":true},{"managed":false,"roles":[],"name":"VoHiYo","id":"292812429992263690","require_colons":true},{"managed":false,"roles":[],"name":"Kappa","id":"292812798050828288","require_colons":true},{"managed":false,"roles":[],"name":"horatio","id":"324359234315878400","require_colons":true},{"managed":false,"roles":[],"name":"grimMT2","id":"350738466356723712","require_colons":true},{"managed":false,"roles":[],"name":"grimMT1","id":"351443964118695939","require_colons":true},{"managed":false,"roles":[],"name":"grimGG","id":"351444514042413056","require_colons":true}],"large":false,"application_id":null,"joined_at":"2017-02-17T23:19:32.041000+00:00","verification_level":0,"explicit_content_filter":0,"channels":[{"permission_overwrites":[],"last_message_id":"361665689213206530","last_pin_timestamp":"2017-07-20T00:23:40.932050+00:00","nsfw":false,"parent_id":null,"name":"general","topic":"Still Pondering What \"Tasty Invisible Space\" Has to Do with Ancient Rome","position":0,"id":"153001169793449984","type":0},{"permission_overwrites":[],"nsfw":false,"parent_id":"360874293011283968","name":"Vault 13","bitrate":64000,"position":5,"id":"165583182895251456","user_limit":0,"type":2},{"permission_overwrites":[],"nsfw":false,"parent_id":"360874293011283968","name":"Omega","bitrate":64000,"position":3,"id":"165583564086181888","user_limit":0,"type":2},{"permission_overwrites":[],"nsfw":false,"parent_id":"360874293011283968","name":"Spencer Mansion","bitrate":64000,"position":6,"id":"165583638191276032","user_limit":0,"type":2},{"permission_overwrites":[],"nsfw":false,"parent_id":"360874293011283968","name":"Typhon Primaris","bitrate":64000,"position":4,"id":"165583663256305664","user_limit":0,"type":2},{"permission_overwrites":[],"nsfw":false,"parent_id":"360874293011283968","name":"Tahiti, Magical Place","bitrate":96000,"position":7,"id":"165583707862728704","user_limit":0,"type":2},{"permission_overwrites":[],"nsfw":false,"parent_id":"360874293011283968","name":"Sierra 117 Club","bitrate":96000,"position":0,"id":"165584017108762625","user_limit":0,"type":2},{"permission_overwrites":[],"last_message_id":"361253067829805067","nsfw":false,"parent_id":"360874090317348864","name":"sounds","topic":"Ideas for Sound Clips","position":3,"id":"169183860926447616","type":0},{"permission_overwrites":[{"allow":0,"deny":0,"id":"153001169793449984","type":"role"}],"nsfw":false,"parent_id":"360874293011283968","name":"Hellfire Club","bitrate":64000,"position":8,"id":"194646804963262464","user_limit":0,"type":2},{"permission_overwrites":[],"last_message_id":"342702551126507520","nsfw":false,"parent_id":"360874090317348864","name":"sayings","topic":"We Hate People","position":2,"id":"206642493175889920","type":0},{"permission_overwrites":[],"last_message_id":"346010660439588874","nsfw":false,"parent_id":"360874090317348864","name":"botideas","topic":"Mostly for Asaph","position":4,"id":"251168555364515841","type":0},{"permission_overwrites":[{"allow":0,"deny":0,"id":"153001169793449984","type":"role"}],"nsfw":false,"parent_id":"360874293011283968","name":"Aerozap's Harem (AFK)","bitrate":8000,"position":10,"id":"258412730480984068","user_limit":0,"type":2},{"permission_overwrites":[{"allow":0,"deny":1049600,"id":"153001169793449984","type":"role"},{"allow":1049600,"deny":0,"id":"165948769978810368","type":"role"},{"allow":1049600,"deny":0,"id":"361857158024921099","type":"role"},{"allow":1049600,"deny":0,"id":"196030219512053760","type":"role"}],"nsfw":false,"parent_id":"360874293011283968","name":"Painted World of Ariamis","bitrate":96000,"position":9,"id":"258790882726117386","user_limit":0,"type":2},{"permission_overwrites":[{"allow":0,"deny":0,"id":"153001169793449984","type":"role"}],"nsfw":false,"parent_id":"360874293011283968","name":"Anor Londo","bitrate":96000,"position":1,"id":"264315490476752898","user_limit":0,"type":2},{"permission_overwrites":[],"last_message_id":"360985163666292736","nsfw":false,"parent_id":"360874090317348864","name":"clips","topic":"Twitch and Video Clips","position":1,"id":"338744660614840340","type":0},{"permission_overwrites":[],"nsfw":false,"parent_id":"360874293011283968","name":"Mylta Power","bitrate":96000,"position":2,"id":"344292360504606733","user_limit":0,"type":2},{"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"Topics","position":1,"id":"360874090317348864","type":4},{"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"Voice","position":0,"id":"360874293011283968","type":4}],"name":"Tasty Invisible Space Station","mfa_level":0,"region":"us-east","splash":null}
2017-09-25 10:45:57.507 ERROR 27464 --- [inWS-ReadThread] n.d.jda.core.requests.WebSocketClient    : Encountered an Exception

java.lang.NullPointerException: null
	at net.dv8tion.jda.core.handle.ReadyHandler.guildSetupComplete(ReadyHandler.java:193) ~[NootBot.jar!/:2.5.5]
	at net.dv8tion.jda.core.handle.GuildCreateHandler.lambda$handleInternally$98(GuildCreateHandler.java:44) ~[NootBot.jar!/:2.5.5]
	at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:303) ~[NootBot.jar!/:2.5.5]
	at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:38) ~[NootBot.jar!/:2.5.5]
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37) ~[NootBot.jar!/:2.5.5]
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:969) [NootBot.jar!/:2.5.5]
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:661) [NootBot.jar!/:2.5.5]
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1004) [NootBot.jar!/:2.5.5]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368) [NootBot.jar!/:2.5.5]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270) [NootBot.jar!/:2.5.5]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990) [NootBot.jar!/:2.5.5]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749) [NootBot.jar!/:2.5.5]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [NootBot.jar!/:2.5.5]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [NootBot.jar!/:2.5.5]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) [NootBot.jar!/:2.5.5]
```

When my bot is initializing after categories update for Discord.

**Comment by MinnDevelopment** [comment] 2017-09-25 14:42
This has nothing to do with categories.
You are using an outdated version of org.json which does not have `JSONArray.forEach` and fails to initialize due to that.

Duplicate of #448 #454 #466

**Closed by MinnDevelopment** 2017-09-25 14:42 UTC
