### ISSUE TITLE
Response Code 400 when using TextChannel#deleteMessages

### ISSUE THREAD

**Issue by Macoonier** [DV8FromTheWorld/JDA#358] opened 2017-05-16 13:27 UTC
I'm not quite sure why this is happening but my piece of code should be correct.
```java
int totalMessages = amount + 1;
List<Message> messagesToDelete = new ArrayList<>();

do {
	int historyToGet = Math.min(MAX_HISTORY, totalMessages);
	List<Message> history = channel.getHistory().retrievePast(historyToGet).complete();
	messagesToDelete.addAll(history);
	totalMessages -= historyToGet;
} while (totalMessages > 0);

while (messagesToDelete.size() > 100) {
	List<Message> part = messagesToDelete.subList(0, 100);
	textChannel.deleteMessages(part).complete();
	
	for (int i = 0; i < part.size(); i++) {
		messagesToDelete.remove(i);
	}
}

textChannel.deleteMessages(messagesToDelete)
    .queue(callback -> 
        channel.sendMessage("Deleted ``" + amount + "`` messages!").queue(msg -> new MessageDeleteTask(msg, 4 * 1000))
);
```

```
[15:22:23] [Fatal] [JDA]: net.dv8tion.jda.core.exceptions.ErrorResponseException: 400: {"messages": ["58"]}
	at net.dv8tion.jda.core.exceptions.ErrorResponseException.create(ErrorResponseException.java:131)
	at net.dv8tion.jda.core.requests.Request.onFailure(Request.java:73)
	at net.dv8tion.jda.core.entities.impl.TextChannelImpl$1.handleResponse(TextChannelImpl.java:91)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:159)
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:303)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MinnDevelopment** [comment] 2017-05-16 18:04
Is it possible that you are trying to delete messages older than 2 weeks?

**Comment by Macoonier** [comment] 2017-05-17 15:19
No, the server was created one day before.

**Comment by MinnDevelopment** [comment] 2017-05-17 15:45
I am unable to reproduce this, I need more information to be able to figure this one out.

**Comment by Dunciboy** [comment] 2017-06-02 19:56
@MinnDevelopment I might be wrong but this seems the be an error coming from queue() if I look at the stack trace, all the delete actions in the code he send are complete() actions except for the message he sends.

**Comment by DV8FromTheWorld** [comment] 2017-07-08 04:23
There has been no comments on this issue for basically 2 months (besides Dunciboy's).
As far as I know, this isn't a JDA issue. Have their been any updates to prove otherwise?

**Comment by MinnDevelopment** [comment] 2017-07-14 10:18
As this has not been updated in a week I am closing this.
If this is not resolved, feel free to reopen this issue with more detail/research.

**Closed by MinnDevelopment** 2017-07-14 10:18 UTC
Labels: need more info

**Comment by Kris-kun** [comment] 2017-12-30 15:24
I got the same problem and found the error. In your list **messagesToDelete**, at least one messages is twice in there. **This is not allowed.** Be sure to have a message only **once** in your list when calling channel.deleteMessages(...).

For this specific problem (even though you may not need it anymore):
If you loop through your do-while twice, you'll get the same messages because you call channel.getHistory() twice. This creates a new history. You would have to save the history temporary and use the same history twice instead of creating a new one.

**Comment by kantenkugel** [comment] 2017-12-30 15:27
@Kris-kun thanks for this clarification! This will probably solve some future issues.
