### ISSUE TITLE
jdaBuilder.build() just freezes

### ISSUE THREAD

**Issue by taminoelgert** [DV8FromTheWorld/JDA#2142] opened 2022-05-28 12:15 UTC
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

When calling jdaBuilder.build() I expect it to connect to the discord API.
Instead, the bot just gets stuck at net.dv8tion.jda.api.events.http.HttpRequestEvent@1636c018. The exact same problem already existed under: (https://github.com/DV8FromTheWorld/JDA/issues/350)
And was then solved with a downrade to a Version 3.x . However, I really don't want to downgrade to an old version that isn't even in the maven repo anymore.

Event Log:
StatusUpdate(INITIALIZING->INITIALIZED)
StatusUpdate(INITIALIZED->LOGGING_IN)
net.dv8tion.jda.api.events.http.HttpRequestEvent@1636c018

### Code Example for Reproduction Steps

```java
<dependency>
   <groupId>net.dv8tion</groupId>
   <artifactId>JDA</artifactId>
   <version>5.0.0-alpha.12</version>
</dependency>
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.OnlineStatus;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.events.GenericEvent;
import net.dv8tion.jda.api.events.ReadyEvent;
import net.dv8tion.jda.api.hooks.EventListener;
import net.dv8tion.jda.api.utils.cache.CacheFlag;

import javax.security.auth.login.LoginException;


public class ReadyListener implements EventListener {
    public static JDA start(String token) throws LoginException {
        JDABuilder jdaBuilder = JDABuilder.createDefault(token);
        jdaBuilder.addEventListeners(new ReadyListener());
        JDA jda = jdaBuilder.build();
        return jda;
    }
    @Override
    public void onEvent(GenericEvent event)
    {
        System.out.println(event.toString());
    }
}
```

### Exception or Error

```yesyes
There are no mistakes, just nothing happens anymore.
```

**Comment by freya022** [comment] 2022-05-28 12:21
You need to upgrade your JDK, you need 17.0.2+, 17.0.1 is bugged

**Comment by MinnDevelopment** [comment] 2022-05-28 12:22
Potential duplicate of #1858

**Comment by taminoelgert** [comment] 2022-05-28 12:40
> You need to upgrade your JDK, you need 17.0.2+, 17.0.1 is bugged

I use openjdk-17.0.2

**Comment by taminoelgert** [comment] 2022-05-28 12:43
> Potential duplicate of #1858
Runs on my Linux server with 24 cores and 32 GB RAM in the Docker container...

**Comment by MinnDevelopment** [comment] 2022-05-28 12:45
1. Please try the code suggested in #1858 and see if it works
2. If not, please provide a [thread dump](https://github.com/DV8FromTheWorld/JDA/wiki/10\)-FAQ#how-do-i-make-a-thread-dump) and full console logs

**Comment by taminoelgert** [comment] 2022-05-28 12:53
Understood. The bot works with more than one assigned core in kubernetes great. The solution described in (https://github.com/DV8FromTheWorld/JDA/issues/1858) works as well. But, contrary to what is described in this ticket, the error does not seem to be gone with java 17.0.2.

**Comment by MinnDevelopment** [comment] 2022-05-28 12:59
You can also try using a different distribution of the JDK, such as the latest release of [Temurin](https://github.com/adoptium/temurin17-binaries/releases/).

If you have any additional comments though, make sure to use #1858 so all information is in one place.

**Closed** 2022-05-28 12:58 UTC
