### ISSUE TITLE
Why i get throw error on MessageReceivedEvent when i use event#getGuild

### ISSUE THREAD

**Issue by OMAR-3OOV** [DV8FromTheWorld/JDA#1941] opened 2021-12-08 23:53 UTC
[download]: https://bintray.com/dv8fromtheworld/maven/JDA/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[wiki]: https://github.com/DV8FromTheWorld/JDA/wiki
[FAQ]: https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ

## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download]
- [x] I have checked the [wiki] and especially the [FAQ] section for similar questions.

## Question

I just use **event#getGuild()** on **MessageReceivedEvent**, and get the error `IllegalStateException: This message event did not happen in a guild`, as someone said this bug is fixed :/, so why I'm getting this throw error, my current version use is `5.0.0-alpha.2`
## Example Code

`event#getTextChannel("the guild for this channel is " + event#getGuild().getName()).queue();`

**Comment by Tais993** [comment] 2021-12-09 00:08
> What is the version shown by JDAInfo.VERSION?

**Comment by OMAR-3OOV** [comment] 2021-12-09 01:00
> > What is the version shown by JDAInfo.VERSION?
> 
> _And your example code doesn't even compile_

whatever bro I just write random thing, I just want to know why it throws error, this simple things doesn't effect

**Comment by Tais993** [comment] 2021-12-09 01:06
Issue is we can't help you, we've no info, and you don't seem to listen.
So I'll ask it again, can you screenshot the return value of `JDAInfo.VERSION`?

**Comment by MinnDevelopment** [comment] 2021-12-09 01:09
This error happens when you try using `event.getGuild()` on a message event from a private channel. This is intended behavior, and the exception message and [documentation](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/events/message/GenericMessageEvent.html#getGuild()) make this clear.

Since you haven't provided reproduction steps, a proper code example, or a professional attitude, I'm closing this issue as resolved.

**Closed by MinnDevelopment** 2021-12-09 01:09 UTC
