### ISSUE TITLE
CheckPermissions throws exception even though bot has permission.

### ISSUE THREAD

**Issue by Dunciboy** [DV8FromTheWorld/JDA#336] opened 2017-04-28 19:14 UTC
`net.dv8tion.jda.core.exceptions.PermissionException: Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_WRITE
        at net.dv8tion.jda.core.entities.impl.TextChannelImpl.checkPermission(TextChannelImpl.java:606)
        at net.dv8tion.jda.core.entities.impl.TextChannelImpl.checkPermission(TextChannelImpl.java:598)
        at net.dv8tion.jda.core.entities.impl.TextChannelImpl.sendFile(TextChannelImpl.java:297)
        at net.dv8tion.jda.core.entities.MessageChannel.sendFile(MessageChannel.java:490)`

The bot is trying to send a file to a channel where it has permission override access by role.
I tried sending a normal message as well same issue.
giving the bot override permissions directly does not throw an exception, giving the role global permission to send messages also doesn't throw an exception.
Removing and adding the role to allow it send messages does not solve this issue and throws an exception.

Rebooting the bot solves this issue, but after some time lets say around 2-4 days the permissions check system fails again. I have 2 bots running the exact same code first bot 1 failed and then later while I was testing the above the other bot also started failing at checking it's role permission override.

I'm on build 183, I will update to the latest build and report in if the issue repeats again. This is the 3rd time this issue has occurred.

**Comment by kantenkugel** [comment] 2017-04-28 21:49
Ther role override with the permission grant: does it allow only file attachment or the general message write too?

**Comment by Dunciboy** [comment] 2017-04-28 21:54
Both, but the issue is the permission to write messages to the channel.

**Comment by Dunciboy** [comment] 2017-04-30 22:06
I also seem to be having issues with updating perms for override permission on channels, updating them causes the existing permissions that are not modified to be cleared.

**Comment by MinnDevelopment** [comment] 2017-05-01 04:34
That is intended behaviour

**Comment by Dunciboy** [comment] 2017-05-01 08:45
@MinnDevelopment Would it be possible to make that clear because when i check the `textChannel.getPermissionOverride(event.getGuild().getPublicRole()).getManager().grant(Permission.MESSAGE_READ, Permission.MESSAGE_HISTORY).queue();`
Docs for grant and it's associated class I don't immediately see anything about all the perms being wiped also what's the point of .clear it's going to clear everything anyway?

**Comment by MinnDevelopment** [comment] 2017-05-01 09:15
We plan to redesign the managers in an upcoming version, this can be changed thus it is not really something I plan to document for now.

**Comment by Dunciboy** [comment] 2017-05-01 09:22
I see but i was using them for an event and then suddenly during the event the owner tells me hey, your bot it removing my existing permission. So because of that the entire event the owner of the event had to manually set no write_permission every time a new channel was visible associated with the event.

Back to the original problem what more information would you guys need for the check permission issue?

**Comment by Frederikam** [comment] 2017-05-03 21:25
I am also experiencing this. Invoking `/channels/:channelId/messages` works fine, and curiously the bot can also send typing. This bot is running `3.0.0_185`.

Permissions for this particular channel is set up like this:

- The server's default role's only permission grant is `MESSAGE_WRITE`.
- The bot's only role (excluding the default role) does not grant `MESSAGE_WRITE`.
- The channel's default role denies `MESSAGE_WRITE`.
- The bot's only role override for that channel grants `MESSAGE_WRITE` and manage channel.

**Comment by DV8FromTheWorld** [comment] 2017-05-03 22:15
Can y'all test this using #324 ? The permission changes there may already take this problem into account.

**Comment by Dunciboy** [comment] 2017-05-07 04:57
@DV8FromTheWorld Does build 187 include this update?

**Comment by Dunciboy** [comment] 2017-05-08 21:49
I can say that since using [This version](https://github.com/DV8FromTheWorld/JDA/commit/6811d374879ae2a40c3864749aaf084c228394cf) I haven't encountered the problem again for at least 4 days.

**Comment by MinnDevelopment** [comment] 2017-05-08 21:49
That is not a test version. `bug/permission-util` is a test version.

**Comment by MinnDevelopment** [comment] 2017-05-09 08:23
Does this still happen on our latest build `193`?

**Comment by Dunciboy** [comment] 2017-05-10 10:05
On this build now it usually happend between 3 -5 days. I'll provide you with information then.

**Comment by MinnDevelopment** [comment] 2017-05-10 12:15
That build was released 2 days ago. How can it be 3-5 days?

**Comment by Dunciboy** [comment] 2017-05-10 12:17
I think you are misunderstanding me @MinnDevelopment.

**Comment by Dunciboy** [comment] 2017-05-13 17:58
Both my bots running on build 193 have been online for 5 days now and daily have been posting images in a channel that is only accessible due to override permissions assigned by role, have not gotten any issues during the testing period.

**Comment by MinnDevelopment** [comment] 2017-05-14 13:41
This appears to be fixed by the recent permission changes of build `193`

**Closed by MinnDevelopment** 2017-05-14 13:41 UTC
Labels: priority, requires testing
