### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.countMatches(Ljava/lang/CharSequence;C)I

### ISSUE THREAD

**Issue by supertassu** [DV8FromTheWorld/JDA#188] opened 2016-11-23 12:25 UTC
Hi. I am trying to get this working with [spigot](https://www.spigotmc.org/) and this is giving this strange error: 

```
java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.countMatches(Ljava/lang/CharSequence;C)I
        at net.dv8tion.jda.core.requests.Route.<init>(Route.java:162) ~[?:?]
        at net.dv8tion.jda.core.requests.Route.<init>(Route.java:33) ~[?:?]
        at net.dv8tion.jda.core.requests.Route$Self.<clinit>(Route.java:37) ~[?:?]
        at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:147) ~[?:?]
        at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:105) ~[?:?]
        at net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:355) ~[?:?]
        at net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:378) ~[?:?]
        at org.supertassu.tyhjyydensyoma.api.discord.Discord.<init>(Discord.java:24) ~[?:?]
        at org.supertassu.tyhjyydensyoma.api.TyhjyydensyomaAPI.onEnable(TyhjyydensyomaAPI.java:25) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-72c2605-33071ec]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.10.2.jar:git-Spigot-72c2605-33071ec]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-72c2605-33071ec]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2.jar:git-Spigot-72c2605-33071ec]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2.jar:git-Spigot-72c2605-33071ec]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-72c2605-33071ec]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-72c2605-33071ec]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-72c2605-33071ec]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-72c2605-33071ec]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-72c2605-33071ec]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] 
``` 

My POM.xml: http://pastebin.com/S65JB5aC
My code: http://pastebin.com/2PZpdGAt

**Comment by DV8FromTheWorld** [comment] 2016-11-23 18:07
You have a conflicting version of apache lang3 installed. I imagine that spigot comes with a version of it as well

**Comment by supertassu** [comment] 2016-11-24 04:47
Oh. Spigot comes with 2.5.

**Comment by DV8FromTheWorld** [comment] 2016-11-24 07:47
Wow.. that's out of date. JDA uses `3.5`

**Comment by DV8FromTheWorld** [comment] 2016-11-24 07:49
As this isn't a JDA issue, I am closing it.

**Closed by DV8FromTheWorld** 2016-11-24 07:49 UTC
Labels: help wanted

**Comment by ZeroxTV** [comment] 2017-01-04 17:08
This actually is an issue, because char doesn't equal char sequence. You use something like countMatches(route, '{'). I downloaded the source and changed the ' to " and everything works perfectly because a String is a Charsequence, but a single char is not. The method countMatches requires two charsequences.

**Comment by MinnDevelopment** [comment] 2017-01-04 17:40
Version 3.4 introduced a method that allows to provide a character as second parameter.
Version 3.0 introduced a method that allows two `CharSequence` parameters.
Both are available in the version that JDA uses `3.5`.

**Comment by Sxtanna** [comment] 2017-03-27 16:46
@DV8FromTheWorld Could someone possibly add some sort of solution to this, this issue was brought to me by someone who was using my dependency library, and them having to shade lang3 by using relocation sort of defeats the purpose, can we get some backwards compatibility?

**Comment by ArsenArsen** [comment] 2017-03-27 16:59
There is a solution. When shading move the commons package that JDA uses.

**Comment by DV8FromTheWorld** [comment] 2017-03-28 04:06
Shading *is* the solution.
What you're asking from me is the same as if you were to ask spigot to update from `2.5` to `3.5`. They would tell you to shade.

It is not JDA's responsibility to be interopt with another program, especially due to them using an out of date version of an extremely old lib. Both situations just call for shading.

**Comment by ArsenArsen** [comment] 2017-03-28 07:26
Yes. Mojang does. Does it matter? No. Just relocate JDAs commons Lang when shading your plugin. It isn't hard. And there is absolutely no reason for the dependency to be outdated by JDA. It would make more problems than solutions. Very small part of the user are is on spigot, and changing the version of that fundamental library is a waste of time. As said before just shade and relocate the one uses by JDA. I think the discussion right now is pointless. That's the solution.. Or make Mojang update, but good luck with that.

**Comment by Sxtanna** [comment] 2017-03-28 12:58
I was only saying that for clarification and to show how improbable it would be for us to update it. Also I'm not asking for you guys to downgrade it..
 
![image](https://cloud.githubusercontent.com/assets/20979389/24405695/cdf767e8-1393-11e7-9c09-c0d5e00f4120.png)

In lang3 3.5, there's 2 methods for countMatches, one of them is new, and the other one is older. By using the older one you would retain backwards compatibility while also retaining intended functionality. It's a very simple solution to an issue blown way out of proportion and  all I'm asking is to have it considered.

### For clarification:
countMatches(CharSequence, Char) is the one currently in use by JDA
countMatches(CharSequence, CharSequence) is the one I'm asking to be used instead, as it is in all of the versions, and not just the newer one

**Comment by MinnDevelopment** [comment] 2017-03-28 13:05
JDA will not downgrade to an older version. Shading your versions is something that you have to do. 
Period.

We know about this change, I even [mentioned](https://github.com/DV8FromTheWorld/JDA/issues/188#issuecomment-270434583) it above in this very issue.
We do not intend to change the method. If you want to use JDA you will have to properly shade your dependencies, this issue is only caused by colliding dependencies and just because JDA uses the older method doesn't mean it resolves the main issue.

Your issue is not caused by JDA it is caused by your setup.

**Comment by MinnDevelopment** [comment] 2017-03-28 13:07
**In addition**
`StringUtils.countMatches` is not the only method from 3.5 that JDA is using.

**Comment by Sxtanna** [comment] 2017-03-28 13:53
The 2 methods being used that would conflict are 
 * countMatches
 * truncate

the former being an easy fix, and the latter can simply be replaced with subString...

Also, is the entire lang3 library being shaded in JDA for only 6-7 methods and 2 classes? 
@MinnDevelopment @DV8FromTheWorld

**Comment by Almighty-Alpaca** [comment] 2017-03-28 13:56
@Sxtanna if you don't want to shade a whole lib than just shade the affected classes.

**Comment by DV8FromTheWorld** [comment] 2017-03-28 18:31
So here is a bigger thing that you're missing: you're asking us to use the 2.5 method because the 3.5 method doesn't exist in the already included 2.5 version with MC, but the fact that it complains that the 3.5 method doesn't exist is because NONE of the 3.5 is loaded. 
We use 3.5 in other places in JDA, thus it not being loaded will break JDA.

I've detailed why this happens here: http://stackoverflow.com/a/41629406/3813641
Yes, this is for MinecraftForge, but the exact same concept exists for Spigot.

The first use of 3.5 is encountered with countMatches, so that is the perceived point of failure, but it is a larger problem.

I do find it curious: why do you not want to shade? We've brought it up multiple times and each time you have skipped past it and pushed for us to change our usage. What do you not want to shade?

**Comment by Sxtanna** [comment] 2017-03-28 18:43
I know that shading and relocating the needed classes is a fix, however its overkill. 

https://gist.github.com/Sxtanna/a9b67bd2b5b663de73a00fdf648013a3

Here I've shown everywhere lang3 is used in JDA, the only 2 things that are in 3.5 that aren't in 2.5 are 
- countMatches(CharSequence, Char)
and
- truncate(String, int)

Which are both in StringUtils, its the only class that is different (in this case)

Countmatches is used once, and truncate is used twice, replacing countMatches with the one that will allow backwards compatibility would change nothing functionality wise, and replacing the two truncate methods (which in their usages do basically the same thing and should be pulled into a method of its own anyway), would be a simple refactor. 

I also find it curious how backwards compatibility isn't something that's a tleast considered, and just thrown out for the reason of "just shade it yourself"? @DV8FromTheWorld

**Comment by DV8FromTheWorld** [comment] 2017-03-28 18:45
Additionally, we use lang3 for
- Pair
- MutablePair
- ExceptionUtils
- StringUtils
  - countMatches
  - truncate
  - equals
  - equalsIgnoreCase

But that really should matter. Why we use a lib or dont has nothing to do with this conversation.

**Comment by Sxtanna** [comment] 2017-03-28 18:46
Everything there is listed in the gist I posted. And you're right, I never question why you were using lang3, I asked if JDA was shading the entire thing, or just the needed classes?

**Comment by Almighty-Alpaca** [comment] 2017-03-28 18:47
JDA isn't shading anything

**Comment by DV8FromTheWorld** [comment] 2017-03-28 18:50
I was on mobile and your post wasn't on my screen when I typed my list.
It has nothing to do with 'not supporting backwards compatibility', the factor the matter is what if we decide to start using something that DOESNT exist in 2.5? What will you do then?

I get wanting backwards compatibility, but it isn't always best to bend yourself for it. This is such a case. Shading is *not* overkill. Why do you believe it is overkill? What reason do you have for not shading? Your plugin will have to have JDA in it anyways.

**Comment by DV8FromTheWorld** [comment] 2017-03-28 18:52
The point is you should setup a system that will work no matter what happens. Shading will safeguard against future changes in JDA using other features, not only with lang3, but also any other dependencies that we might end up using.

**Comment by Sxtanna** [comment] 2017-03-28 19:03
What do you mean by "bend yourself for it"? 

Also the reason in this case is because distributing large jars with all dependencies shaded is usually not great xD. So I made a util that will download and load them at runtime. I honestly didn't even know JDA was a thing before someone told me it was incompatible. 
With the Util, the plugin will have nothing in it, but its own compile output. JDA will be downloaded, and all dependencies will be downloaded aswell.

**Comment by Almighty-Alpaca** [comment] 2017-03-28 19:10
why don't you just add support for relocating dependencies to your dependency-loader then?

**Comment by Sxtanna** [comment] 2017-03-28 19:12
It doesn't modify files. It's supposed to be simple and as small as possible.

**Comment by MinnDevelopment** [comment] 2017-03-28 19:13
Do you plan to contact every incompatible lib dev team to downgrade dependencies for your dependency loader?

**Comment by Sxtanna** [comment] 2017-03-28 19:14
I never proposed downgrading anything actually... Only to consider backwards compatibility when creating APIs.

**Comment by Almighty-Alpaca** [comment] 2017-03-28 19:15
which is essentially the same...

**Comment by Sxtanna** [comment] 2017-03-28 19:15
How is that the same?

**Comment by Almighty-Alpaca** [comment] 2017-03-28 19:17
where is the difference between using an old version and using a new version but only the old features of it?

**Comment by Sxtanna** [comment] 2017-03-28 19:21
In this specific case the only new feature you're using is #truncate which is literally just a wrapper for subString. So the least that can be done is to use the method that is going to be in all versions...

**Comment by Almighty-Alpaca** [comment] 2017-03-28 19:23
that doesn't answer my question though...

**Comment by Sxtanna** [comment] 2017-03-28 19:24
Your question was insinuating something that isn't pertinent in this specific case, so I chose to explain what we're dealing with rather than what you're trying to imply.

**Comment by TechXcrafter** [comment] 2017-05-09 13:17
Sorry to bring this up again but I would like to know how I can move or relocate the dependency.

Having the same issue but don't know how to fix it.

**Comment by Sxtanna** [comment] 2017-05-09 13:18
@TechXcrafter Use class relocation.
https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html

**Comment by TechXcrafter** [comment] 2017-05-09 13:26
Currently my pom.xml looks like this:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.TechXcrafter</groupId>
    <artifactId>DiscordBridge</artifactId>
    <version>1.0</version>


    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>jcenter</id>
            <name>jcenter-bintray</name>
            <url>http://jcenter.bintray.com</url>
        </repository>
    </repositories>
    <dependencies>
        
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.11.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>org.bukkit</groupId>
            <artifactId>bukkit</artifactId>
            <version>1.11.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.TechXcrafter</groupId>
            <artifactId>TechPluginLibrary</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>net.lingala.zip4j</groupId>
            <artifactId>zip4j</artifactId>
            <version>1.3.2</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.5</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.0.1</version>
        </dependency>


        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>3.0.0_191</version>
        </dependency>

    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>`

So and I need to add this part right:
`<executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <relocations>
                <relocation>
                  <pattern>org.codehaus.plexus.util</pattern>
                  <shadedPattern>org.shaded.plexus.util</shadedPattern>
                  <excludes>
                    <exclude>org.codehaus.plexus.util.xml.Xpp3Dom</exclude>
                    <exclude>org.codehaus.plexus.util.xml.pull.*</exclude>
                  </excludes>
                </relocation>
              </relocations>
            </configuration>
          </execution>
        </executions>`

But what do I need to put in these fields?

Btw thank you for this fast answer

**Comment by TechXcrafter** [comment] 2017-05-09 13:37
Now my pom.xml looks like this. Still not working.
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.TechXcrafter</groupId>
    <artifactId>DiscordBridge</artifactId>
    <version>1.0</version>


    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>jcenter</id>
            <name>jcenter-bintray</name>
            <url>http://jcenter.bintray.com</url>
        </repository>
    </repositories>
    <dependencies>
        
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.11.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>org.bukkit</groupId>
            <artifactId>bukkit</artifactId>
            <version>1.11.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.TechXcrafter</groupId>
            <artifactId>TechPluginLibrary</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>net.lingala.zip4j</groupId>
            <artifactId>zip4j</artifactId>
            <version>1.3.2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.5</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.0.1</version>
        </dependency>


        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>3.0.0_191</version>
        </dependency>

    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
                                <relocation>
                                    <pattern>org.apache.commons.lang</pattern>
                                    <shadedPattern>org.shaded.commons.lang</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>`

Thanks for helping

**Comment by MinnDevelopment** [comment] 2017-07-28 14:26
JDA no longer uses lang3 as of 2d19f09 which should resolve these dependency issues.
