### ISSUE TITLE
JDARequester error on shutdown

### ISSUE THREAD

**Issue by JesusCrie** [DV8FromTheWorld/JDA#405] opened 2017-07-23 19:35 UTC
Hi, i have a huge error (3 excaly) when i use the #shutdown() method.
Sometime it occurs and sometimes everything is fine.

[Here is my class](https://github.com/JesusCrie/DeusVultBot/blob/dev/src/main/java/com/jesus_crie/deusvult/DeusVult.java)

Here is the full error
```[21:32:08] [Fatal] [JDARequester]: Encountered an exception:
[21:32:08] [Fatal] [JDARequester]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@60182565 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@6edfd716[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 18]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at net.dv8tion.jda.core.requests.Request.onSuccess(Request.java:59)
	at net.dv8tion.jda.core.entities.MessageChannel$1.handleResponse(MessageChannel.java:375)
	at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:166)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:186)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:86)
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[21:32:08] [Fatal] [JDARequester]: Requester system encountered an internal error
[21:32:08] [Fatal] [JDARequester]: Encountered an exception:
[21:32:08] [Fatal] [JDARequester]: java.lang.RuntimeException: An error occurred while parsing the response for a RestAction
	at net.dv8tion.jda.core.requests.Response.<init>(Response.java:89)
	at net.dv8tion.jda.core.requests.Response.<init>(Response.java:43)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:195)
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:86)
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: closed
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:417)
	at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:59)
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:266)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at net.dv8tion.jda.core.requests.Requester.getBody(Requester.java:248)
	at net.dv8tion.jda.core.requests.Response.<init>(Response.java:66)
	... 11 more

[21:32:08] [Fatal] [JDARequester]: Requester system encountered an internal error from beyond the synchronized execution blocks. NOT GOOD!
[21:32:08] [Fatal] [JDARequester]: Encountered an exception:
[21:32:08] [Fatal] [JDARequester]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4681d01c rejected from java.util.concurrent.ScheduledThreadPoolExecutor@6edfd716[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 18]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at net.dv8tion.jda.core.requests.Request.onFailure(Request.java:90)
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:322)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by Almighty-Alpaca** [comment] 2017-07-23 19:37
quality issue :ok_hand:

**Comment by JesusCrie** [comment] 2017-07-23 19:38
it was a missclick ^^

**Comment by Almighty-Alpaca** [comment] 2017-07-23 19:40
np

should be fixed by updating to latest  version

**Comment by JesusCrie** [comment] 2017-07-23 19:42
I use version 3.2.0_234

**Comment by MinnDevelopment** [comment] 2017-07-23 20:03
The second exception is caused by the first exception.
This seems to be caused by the pool threads timing out before finishing the executions of some rest actions.
If you can reproduce this consistently you might want to consider doing the following:
```java
// api is an instance of JDA
api.getRegisteredListeners().forEach(api::removeEventListener);
Thread.sleep(2000); // sleep 2 seconds to ensure all tasks have finished
api.shutdown();
```
In addition to that I suggest you try to lower the amount of rest requests you do per second as this can only be caused by lots of requests being made in a sequence causing much traffic to handle by the rate limit handler.

**Comment by JesusCrie** [comment] 2017-07-23 20:17
It's strange, i have only one listener for MessageReceivedEvent, i only send requests when a command is triggered (mainly).
The only reason i see is a post request to save my config that is done through apache but this make no sense.

**Comment by JesusCrie** [comment] 2017-07-23 20:27
I think i've found the issue, i send a message with a #queue() just before #shutdown()

Thanks all !

**Closed** 2017-07-23 20:27 UTC
