### ISSUE TITLE
Question ChannelManager (VoiceChannel)

### ISSUE THREAD

**Issue by manercraft** [DV8FromTheWorld/JDA#231] opened 2017-01-10 13:38 UTC
Hello,
How set UserLimit unlimited from a ChannelManager of a VoiceChannel ?
0 not working
Thank

![totermw_2017-01-10_14-38-17](https://cloud.githubusercontent.com/assets/1338257/21808199/79b7a702-d742-11e6-80e2-561001c969e5.jpg)

**Comment by Dragorn421** [comment] 2017-01-10 15:31
@MinnDevelopment the problem is here : https://github.com/DV8FromTheWorld/JDA/blob/620e380c424af6d0fc9f992a2ef0c4e37853ba03/src/main/java/net/dv8tion/jda/core/managers/ChannelManagerUpdatable.java#L203
The condition should be `if (value < 0 || value > 99)`
According to the discord documentation ( https://discordapp.com/developers/docs/resources/channel#modify-channel ) 0 is allowed and means no user limit.

**Comment by Almighty-Alpaca** [comment] 2017-01-10 20:59
Fixed as of bea3fb0. The fix is in build `3.0.BETA2_120`.

**Closed** 2017-01-10 22:07 UTC
Labels: bug, help wanted, question
