### ISSUE TITLE
Bot dont run on vserver

### ISSUE THREAD

**Issue by Seblofs** [DV8FromTheWorld/JDA#1082] opened 2019-08-11 21:24 UTC
When i try to start my Bot on my vserver, that error cames:
Exception in thread "main" java.lang.NoClassDefFoundError: net/dv8tion/jda/core/JDABuilder
        at core.Main.main(Main.java:22)
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.core.JDABuilder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
The crazy thing is, that is run on my local pc.

**Comment by MinnDevelopment** [comment] 2019-08-11 21:26
Duplicate of #101 

This is not a bug in JDA. Fix your setup.

**Closed by MinnDevelopment** 2019-08-11 21:26 UTC

**Comment by Seblofs** [comment] 2019-08-12 08:43
![image](https://user-images.githubusercontent.com/40692731/62853902-0bef9600-bcee-11e9-96f7-5f3c09aed1a2.png)
it is in the JAR!
