### ISSUE TITLE
Bot joining and leaving a VoiceChannel indefinitely

### ISSUE THREAD

**Issue by iBlitzkriegi** [DV8FromTheWorld/JDA#221] opened 2016-12-18 20:15 UTC
Using this code
```
        JDA jda = bots.get(vBot.getSingle(e));
        TrackScheduler trackScheduler = EffLogin.trackSchedulers.get(vBot.getSingle(e));
        AudioManager manager = jda.getVoiceChannelById(vID.getSingle(e)).getGuild().getAudioManager();
        manager.openAudioConnection(jda.getVoiceChannelById(vID.getSingle(e)));
        Guild g = jda.getVoiceChannelById(vID.getSingle(e)).getGuild();
        g.getAudioManager().setSendingHandler(new AudioPlayerSendHandler(trackScheduler.getPlayer()));
```
(Ik I'm getting the voice channel three times rather than making a variable pls nu sass)
But after I used this and joined a voice channel the bot started doing this: https://gyazo.com/a1c128c69b1271d2ab9035c2a06d60f2 and this loop seems to be infinite..

**Comment by DV8FromTheWorld** [comment] 2016-12-19 02:05
Like I told you, use a ConnectionListener + onStatusChange and show me what it outputs during these "loops"

**Comment by MinnDevelopment** [comment] 2016-12-26 15:12
I request an update on this issue, does this still happen?
Is this consistent? How can you reproduce it? Do you have more information (ConnectionListener)?

**Comment by MinnDevelopment** [comment] 2017-01-01 21:59
Closing this due to missing information, if this happens again please re-open with further information.

**Closed by MinnDevelopment** 2017-01-01 21:59 UTC
Labels: need more info
