### ISSUE TITLE
Getting the guild member from a MessageReactionRemoveEvent always returns null

### ISSUE THREAD

**Issue by hex-agon** [DV8FromTheWorld/JDA#1275] opened 2020-04-23 16:40 UTC
## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

The method `getMember()` always return `null` for the event `MessageReactionRemoveEvent` even though the member is still in the guild. The method oddly does return the correct member for the `MessageReactionAddEvent` event.

I've managed to trace this issue since version `4.1.1_111`, any previous version the expected behaviour happens.

### Expected Behavior

The guild member (and is still present in the guild) who removed the reaction is returned.

### Code Example or Reproduction Steps

```
public class ReactionTest implements EventListener {

    public static void main(String[] args) throws Exception {
        new ReactionTest().initialize();
    }

    private void initialize() throws Exception {

        JDA jda = JDABuilder.createDefault("")
                            .build()
                            .awaitReady();

        jda.addEventListener(this);
        System.out.println("Ready");
    }

    @Override
    public void onEvent(@Nonnull GenericEvent event) {

        if (event instanceof GenericMessageReactionEvent) {
            GenericMessageReactionEvent reactionEvent = (GenericMessageReactionEvent) event;

            System.out.println(reactionEvent.getClass().getSimpleName() + " -> member=" + reactionEvent.getMember());
        }
    }
}
```

#### Sample output

```
Ready
MessageReactionAddEvent -> member=MB:Hexagon(U:Hexagon() / G:Hexagon's Bot Testing Ground())
MessageReactionRemoveEvent -> member=null
```

### Code for JDABuilder or DefaultShardManagerBuilder Used

Available in the snippet above

### Exception or Error

N/A

**Comment by MinnDevelopment** [comment] 2020-04-23 16:43
Duplicate of #1261

Discord doesn't provide a member object for reaction remove. If the member isn't cached then we can't provide one here, this is intended behavior and cannot be changed.

You can use `event.getGuild().retrieveMemberById(event.getUserId())` to retrieve a member instance if necessary.

**Closed** 2020-04-23 16:49 UTC
Labels: type: discord issue, wontfix
