### ISSUE TITLE
JDA#shutdown gets blocked on shard death.

### ISSUE THREAD

**Issue by Kodehawa** [DV8FromTheWorld/JDA#312] opened 2017-04-13 21:48 UTC
When doing JDA#shutdown(false) [Attempting to drop a dead shard] or even JDA#shutdown() [when trying to shutdown the whole bot with a dead shard], the shutdown method gets blocked and it never calls the subsequent statements or shuts down the bot at all.
After a shard is dead the only option left is to eval a system exit call and restart the whole bot all over again.

http://i.imgur.com/TEQKzd8.png -> After restarting a shard, it should say "dropped shard x successfully", but it never does. Also weird status changes in between.

**Comment by Frederikam** [comment] 2017-04-13 21:52
Not getting this on `3.0.0_168`. I get a lot of dead shards but I detect and restart them automatically without further problems.

**Comment by Kodehawa** [comment] 2017-04-13 21:55
3.0.0_169 here.

**Comment by MinnDevelopment** [comment] 2017-04-16 20:12
Does this still happen on `3.0.0_176`?
Can you provide a thread dump?

**Comment by ArsenArsen** [comment] 2017-04-16 20:46
I have never gotten this, just putting the info out there.

**Comment by Kodehawa** [comment] 2017-04-16 21:06
I will update, deploy and check. If it hapoens again I will provide the dump

Thanks.

**Comment by MinnDevelopment** [comment] 2017-04-23 20:58
Has this occurred again or am I safe to assume this is a no-issue?

**Comment by Kodehawa** [comment] 2017-04-25 18:19
Happened once more a while ago. Haven't gotten a shard death since though, so cannot check either.

**Comment by Almighty-Alpaca** [comment] 2017-04-29 16:37
It turned out that [jda-nas](https://github.com/sedmelluq/jda-nas) has a bug that caused the thread that calls `AudioManager#closeAudioConnection()` to lock for 1000 seconds (around 16 minutes). As this method is often called from the event thread it locked the reading thread of jda's main websocket. 
Please update jda-nas and report back weather this resolved the issue the issue or not.

**Comment by Kodehawa** [comment] 2017-04-29 16:43
I removed it for now. I'll report back

**Comment by MinnDevelopment** [comment] 2017-05-01 18:28
It turned out that this behaviour can also be caused by #338 . Thus I will keep this open until that issue is resolved and further investigations show this being fixed.

**Comment by MinnDevelopment** [comment] 2017-05-09 08:28
Does this still happen with build `193`?

**Comment by Kodehawa** [comment] 2017-05-09 15:16
Gonna check.

**Comment by MinnDevelopment** [comment] 2017-05-14 13:38
As I haven't received reports of this for 5 days I now close this issue.

**Closed by MinnDevelopment** 2017-05-14 13:38 UTC
Labels: bug, help wanted, On Hold
