### ISSUE TITLE
Message always appear whenever bot tires to send a messsage to minecraft or do anything involving a message

### ISSUE THREAD

**Issue by jakeyhanna** [DV8FromTheWorld/JDA#1771] opened 2021-08-10 22:27 UTC
```[01:15:29 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
        MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"components":[],"attachments":[],"author":{"bot":true,"public_flags":0,"id":"792765541386289162","avatar":"d8f0d2062bb0e598813b0c7e6c83daa4","username":"Jack Alter Ego","discriminator":"5851"},"flags":0,"type":0,"mention_roles":[],"edited_timestamp":null,"content":"","tts":false,"referenced_message":null,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2021-08-01T22:10:38.966000+00:00","roles":["871515080410427432","871515297625018439"],"pending":false,"hoisted_role":null,"deaf":false,"mute":false,"avatar":null,"is_pending":false},"guild_id":"871514844178825246","id":"874778006294523984","embeds":[{"type":"rich","title":"jack1e_hannaJoined the game!"}],"channel_id":"871514844178825249","timestamp":"2021-08-10T22:15:29.290000+00:00"}
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:40) ~[?:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990) ~[?:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
[01:15:29 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
        MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"components":[],"attachments":[],"author":{"bot":true,"public_flags":0,"id":"792765541386289162","avatar":"d8f0d2062bb0e598813b0c7e6c83daa4","username":"Jack Alter Ego","discriminator":"5851"},"flags":0,"type":0,"mention_roles":[],"edited_timestamp":null,"content":"","tts":false,"referenced_message":null,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2021-08-01T22:10:38.966000+00:00","roles":["871515080410427432","871515297625018439"],"pending":false,"hoisted_role":null,"deaf":false,"mute":false,"avatar":null,"is_pending":false},"guild_id":"871514844178825246","id":"874778006294523984","embeds":[{"type":"rich","title":"jack1e_hannaJoined the game!"}],"channel_id":"871514844178825249","timestamp":"2021-08-10T22:15:29.290000+00:00"}
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:40) ~[?:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990) ~[?:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
[01:15:29 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
        MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"components":[],"attachments":[],"author":{"bot":true,"public_flags":0,"id":"792765541386289162","avatar":"d8f0d2062bb0e598813b0c7e6c83daa4","username":"Jack Alter Ego","discriminator":"5851"},"flags":0,"type":0,"mention_roles":[],"edited_timestamp":null,"content":"","tts":false,"referenced_message":null,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2021-08-01T22:10:38.966000+00:00","roles":["871515080410427432","871515297625018439"],"pending":false,"hoisted_role":null,"deaf":false,"mute":false,"avatar":null,"is_pending":false},"guild_id":"871514844178825246","id":"874778006294523984","embeds":[{"type":"rich","title":"jack1e_hannaJoined the game!"}],"channel_id":"871514844178825249","timestamp":"2021-08-10T22:15:29.290000+00:00"}
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:40) ~[?:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990) ~[?:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
[01:15:29 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
        MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"components":[],"attachments":[],"author":{"bot":true,"public_flags":0,"id":"792765541386289162","avatar":"d8f0d2062bb0e598813b0c7e6c83daa4","username":"Jack Alter Ego","discriminator":"5851"},"flags":0,"type":0,"mention_roles":[],"edited_timestamp":null,"content":"","tts":false,"referenced_message":null,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2021-08-01T22:10:38.966000+00:00","roles":["871515080410427432","871515297625018439"],"pending":false,"hoisted_role":null,"deaf":false,"mute":false,"avatar":null,"is_pending":false},"guild_id":"871514844178825246","id":"874778006294523984","embeds":[{"type":"rich","title":"jack1e_hannaJoined the game!"}],"channel_id":"871514844178825249","timestamp":"2021-08-10T22:15:29.290000+00:00"}
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Tuinity-"8e7cc4d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:40) ~[?:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990) ~[?:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
```

**Comment by Tais993** [comment] 2021-08-10 23:13
Minecraft plugin development?

If yes, we can't help you.
It's because Bukkit "closes" your library before all classes got loaded

**Comment by Andre601** [comment] 2021-08-11 00:23
1. Use the templates please. They exist for reasons.
2. Make sure you use the latest dev build of JDA before reporting any issues, as it may already be fixed.
3. Just posting the error alone doesn't give all the context needed. What triggers this? A simple message being sent?

**Comment by jakeyhanna** [comment] 2021-08-11 08:34
> Minecraft plugin development?
> 
> If yes, we can't help you.
> It's because Bukkit "closes" your library before all classes got loaded

Is there a way to note make it write the error atleast?, the bot still works just don't want it to spam thenconsole

**Comment by freya022** [comment] 2021-08-11 10:34
> > Minecraft plugin development?
> > If yes, we can't help you.
> > It's because Bukkit "closes" your library before all classes got loaded
> 
> Is there a way to note make it write the error atleast?, the bot still works just don't want it to spam the console

If its logged as an error, there's probably a reason for why you should fix it instead of ignoring it, it says zip file closed which is a bukkit issue like Andre said, I propose you follow the issue he linked

**Comment by DV8FromTheWorld** [comment] 2021-08-13 15:33
https://github.com/DV8FromTheWorld/JDA/issues/1337

Duplicate of #1761

**Closed by DV8FromTheWorld** 2021-08-13 15:33 UTC
