### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by TheMaskedMonkey** [DV8FromTheWorld/JDA#75] opened 2016-06-25 16:01 UTC
I booted my bot today and it caught this error. To me, it looks like an error with JDA but I could be wrong. Could somebody confirm?

> java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
        at net.dv8tion.jda.utils.PermissionUtil.getEffectivePermission(PermissionUtil.java:215)
        at net.dv8tion.jda.utils.PermissionUtil.getEffectivePermission(PermissionUtil.java:240)
        at net.dv8tion.jda.utils.PermissionUtil.checkPermission(PermissionUtil.java:234)
        at net.dv8tion.jda.utils.PermissionUtil.checkPermission(PermissionUtil.java:129)
        at net.dv8tion.jda.entities.impl.TextChannelImpl.checkPermission(TextChannelImpl.java:289)
        at net.dv8tion.jda.entities.impl.TextChannelImpl.sendMessageAsync(TextChannelImpl.java:208)
        at net.dv8tion.jda.entities.impl.TextChannelImpl.sendMessageAsync(TextChannelImpl.java:200)
        at com.erisbot.listeners.OtherListener.onReady(OtherListener.java:23)
        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:149)
        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.requests.WebSocketClient.ready(WebSocketClient.java:120)
        at net.dv8tion.jda.handle.ReadyHandler.finishReady(ReadyHandler.java:137)
        at net.dv8tion.jda.handle.ReadyHandler.onGuildInit(ReadyHandler.java:122)
        at net.dv8tion.jda.handle.GuildJoinHandler.lambda$handleInternally$45(GuildJoinHandler.java:44)
        at net.dv8tion.jda.handle.EntityBuilder.createGuildFirstPass(EntityBuilder.java:213)
        at net.dv8tion.jda.handle.GuildJoinHandler.handleInternally(GuildJoinHandler.java:38)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:607)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:315)
        at net.dv8tion.jda.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:680)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:243)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:937)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:696)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

**Comment by SasLuca** [comment] 2016-06-25 16:05
@TheMaskedMonkey You are getting a ConcurrentModificationException which means you are trying to modify a List while looping in it using a "for each loop" most likely. This is not because of JDA.

**Comment by TheMaskedMonkey** [comment] 2016-06-25 16:08
I think we've worked out this out, it's still a weird bug and shouldn't of happened.

**Comment by Pear0** [comment] 2016-06-25 16:09
The offending for loop is within JDA. [Link](https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/utils/PermissionUtil.java#L215)

**Comment by TheMaskedMonkey** [comment] 2016-06-25 16:10
I don't do any role checking at startup

**Comment by MinnDevelopment** [comment] 2016-06-25 16:10
I believe it is because the Guild is not fully available yet

**Comment by SasLuca** [comment] 2016-06-25 16:14
@TheMaskedMonkey @Pear0 the problem can not be because of the [https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/utils/PermissionUtil.java#L215](url). The loop in that code snippet does not modify the List. ConcurrentModificationException is only thrown when you modify a List as you loop thru it.

**Comment by Pear0** [comment] 2016-06-25 16:33
@SasLuca It could be modified elsewhere by a separate thread. It's stored in an instance variable Map.
@TheMaskedMonkey You aren't directly calling it, but sendMessageAsync() is.

**Comment by SasLuca** [comment] 2016-06-25 16:38
@Pear0 well then, you should simply not use it in another thread since it's not synchronised. I don't think the developers of JDA use it improperly in their library, but it's hard to tell what the cause of the problem is until @TheMaskedMonkey  does not show us some code.

**Comment by TheMaskedMonkey** [comment] 2016-06-25 16:45
The line which is causing it is this:

`Start.jda.getTextChannelById(Start.configuration.get("logchannelID")).sendMessageAsync("ErisBot v"+Start.VERSION+" started! Running JDA v"+JDAInfo.VERSION, null);`

**Comment by Pear0** [comment] 2016-06-25 16:50
Are you doing anything with roles directly after the line you posted?

**Comment by TheMaskedMonkey** [comment] 2016-06-25 16:50
No, that is literally all that is ran with onReady

**Comment by DV8FromTheWorld** [comment] 2016-06-25 20:37
Interesting error, and super rare in fact. The problem is actually a slight issue inside JDA. Before sending a message, JDA checks if you have permission to send the message. If you're sending a message from outside the event loop (sendMessageAsync or just not from the event thread) then it is -technically- possible to cause this because, unlike when working on the event loop (which blocks next events), working outside that means that JDA will update internal objects while you are working in parallel. In this case, when you went to send a message, JDA checked send permissions like normal, but it seems that and updates for permissions for the guild/channel was received by JDA. Since the message send took place outside of the event loop, it wasn't causing the event block. So the List of permissions was changed while JDA was iterating through it causing this odd bug.

**Comment by Pear0** [comment] 2016-06-25 20:53
@DV8FromTheWorld I've submitted a pull request which should at least fix this issue.

**Comment by DV8FromTheWorld** [comment] 2016-06-26 19:46
Closing this as, for the most part, it would be rare to see this and it should be fixed with @Pear0's recently merged PR.

**Closed by DV8FromTheWorld** 2016-06-26 19:46 UTC
