### ISSUE TITLE
Bug when an event is triggered (using Spigot server to run the bot)

### ISSUE THREAD

**Issue by iInvisibilities** [DV8FromTheWorld/JDA#2197] opened 2022-07-29 13:22 UTC
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

![image](https://user-images.githubusercontent.com/78047131/181769203-845f9cca-25ef-4e37-b98e-ce2d69816b48.png)

### Code Example for Reproduction Steps

```java
you basically  do any event, for example message the bot a PM or send a message in the server or i think anything because whenever i perform an action even joining & leaving a voice channel, it displays error.
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
DABuilder.createDefault(DISCORD_BOT_TOKEN)
                    .setActivity(Activity.listening("new cosmetic suggestions"))
                    .setStatus(OnlineStatus.DO_NOT_DISTURB)
                    .setAutoReconnect(true)
                    .build();
```

### Exception or Error

```yesyes
[14:19:00 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect the following message to the devs:
        JDA 5.0.0-alpha.17_13194f3
        MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"components":[],"attachments":[],"author":{"public_flags":64,"id":"700236653893124196","avatar":null,"username":"INVISIBILITIES","discriminator":"8579","avatar_decoration":null},"flags":0,"type":0,"mention_roles":[],"nonce":"1002565913225986048","edited_timestamp":null,"content":"","tts":false,"referenced_message":null,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2022-07-29T12:29:16.915000+00:00","communication_disabled_until":null,"roles":[],"pending":false,"flags":0,"deaf":false,"mute":false,"avatar":null},"guild_id":"1002553399172149299","id":"1002565913754730546","embeds":[],"channel_id":"1002553399172149302","timestamp":"2022-07-29T13:19:00.613000+00:00"}
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:37) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[Cosmetics-1.0-SNAPSHOT.jar:?]
```

**Comment by freya022** [comment] 2022-07-29 13:24
`java.lang.IllegalStateException: zip file closed` is a common exception that can occur when integrating JDA into a Bukkit/Spigot Plugin.
It simply means that Bukkit unloaded your plugin, but you didn't shut down JDA correctly. That means that some of JDAs Threads/Executors are still running. Because of that, you will receive this error when, for example, JDA received an Event. 

To fix this issue,  `shutdownNow()` your JDA instance in your Bukkit's `onDisable()` method, and block until it's shut down.

```java
jda.shutdownNow();
while (jda.getStatus() != JDA.Status.SHUTDOWN) {
  Thread.sleep(20);
}
```

Design your code in a way that the JDA instance is never used a second time after they've been shut down. (/reload simply calls `onDisable()` and then `onEnable()`  again)

**Comment by MinnDevelopment** [comment] 2022-07-29 13:25
Duplicate of #1429 #1440 #1761 #1771 #1780 #1861

**Closed by MinnDevelopment** 2022-07-29 13:25 UTC
