### ISSUE TITLE
Got an unexpected error

### ISSUE THREAD

**Issue by Eisi05** [DV8FromTheWorld/JDA#2217] opened 2022-08-15 13:39 UTC
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have updated to the [latest JDA version](https://ci.dv8tion.net/job/JDA/lastSuccessfulBuild/)
- [X] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Expected Behaviour

It should Update the Topic of a Text Channel, and it does, but still i get this error

### Code Example for Reproduction Steps

```java
jda.getTextChannelById(Var.discordConsoleID).getManager().setTopic("Online | TPS: " + Lags.getTPS() +
                        " | Player: 0 / " + Bukkit.getMaxPlayers()).queue();
```

### Code for JDABuilder or DefaultShardManagerBuilder used

```java
JDABuilder builder = JDABuilder.createDefault(TOKEN);
```

### Exception or Error

```yesyes
[15:32:29] [JDA MainWS-ReadThread/ERROR]: Got an unexpected error. Please redirect the following message to the devs:
        JDA 5.0.0-alpha.17_13194f3
        CHANNEL_UPDATE -> {"nsfw":false,"rate_limit_per_user":0,"flags":0,"type":0,"guild_hashes":{"metadata":{"hash":"Je9RJA"},"channels":{"hash":"EB2IGw"},"roles":{"hash":"PDqWZg"},"version":1},"permission_overwrites":[{"allow":"0","deny":"2953313361","id":"780161863253622804","type":0},{"allow":"805829713","deny":"0","id":"630712047864381460","type":0},{"allow":"0","deny":"2953313361","id":"645199359222349825","type":0},{"allow":"1040","deny":"2953312321","id":"727514381583384617","type":0},{"allow":"805829713","deny":"0","id":"676426184996945955","type":0},{"allow":"0","deny":"2953313361","id":"818783100451553321","type":0},{"allow":"0","deny":"2953313361","id":"679465061512773654","type":0},{"allow":"0","deny":"2953313361","id":"818776956760883210","type":0},{"allow":"0","deny":"2953313361","id":"597064362863099934","type":0}],"last_message_id":"818800773269815387","parent_id":null,"name":"konsole","hashes":{"metadata":{"hash":"Je9RJA"},"channels":{"hash":"EB2IGw"},"roles":{"hash":"PDqWZg"},"version":1},"guild_id":"597064362863099934","topic":"Online | TPS: 20.0 | Player: [CraftPlayer{name=Eisi05}] / 20","position":0,"id":"676111715678552126"}
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159) ~[spigot-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.dv8tion.jda.internal.handle.ChannelUpdateHandler.handleInternally(ChannelUpdateHandler.java:86) ~[kabubi-1.0-SNAPSHOT.jar:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[kabubi-1.0-SNAPSHOT.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) [kabubi-1.0-SNAPSHOT.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) [kabubi-1.0-SNAPSHOT.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) [kabubi-1.0-SNAPSHOT.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) [kabubi-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) [kabubi-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) [kabubi-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) [kabubi-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) [kabubi-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [kabubi-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [kabubi-1.0-SNAPSHOT.jar:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) [kabubi-1.0-SNAPSHOT.jar:?]
```

**Comment by freya022** [comment] 2022-08-15 13:41
Duplicate of #2205 #2197 #1429 #1440 #1761 #1771 #1780 #1861

**Closed** 2022-08-16 15:48 UTC
